version: '3.8'
services:
  java-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    container_name: java-api
    restart: always
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    restart: always
    volumes:
      - ./db/:/data/db
  mongo-express:
    image: mongo-express
    ports:
        - "8081:8081"
    container_name: mongo-express
    links:
      - mongo-db
    restart: always
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo-db
        - ME_CONFIG_MONGODB_URL=mongodb://mongo-db:27017
volumes:
    data: {}